### ISSUE TITLE
[FEAT] 독도 퍼즐 연동 및 UI 마무리

### ISSUE THREAD

**Issue by Keun04** [pknu-wap/2024_2_WEB_1#73]
### 🏝️Issue
> 전체적인 UI 수정 및 독도 퍼즐 백엔드 연동

### 📆 Development Period
> 2024.11.26~2024.11.28

### 🖥️ Todo
- [x] 독도 퍼즐 백엔드 연동
- [x] Stage4 UI 수정
- [x] 인벤토리 깨짐 수정
- [x] Sortable 확인

### 🧩 Etc.(선택)
 > 기타사항 (참고할 만한 자료, 참고했던 자료, 궁금한 점 등)
